name: Tests

on: [ push, pull_request ]

jobs:
  unit-benchmark-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16'
      - name: Unit Test
        run: go test -gcflags all=-N -l -race -covermode=atomic -coverprofile=coverage.txt ./...
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Benchmark
        run: go test -gcflags all=-N -l -bench=. -benchmem -run=none ./...

  compatibility-test:
    strategy:
      matrix:
        go: [ 1.15, 1.17, 1.18, 1.19 ]
        os: [ X64, ARM64 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Unit Test
        run: go test -gcflags all=-N -l -race -covermode=atomic -coverprofile=coverage.txt ./...

  scenario-test:
    strategy:
      matrix:
        go: [ 1.16, 1.18 ]
    runs-on: [ self-hosted, X64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: x64
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Scenario Tests
        run: |
          cd ..
          rm -rf kitex-tests
          git clone https://github.com/jayantxie/kitex-tests.git
          cd kitex-tests
          ./run.sh ${{github.workspace}}
