name: Tests

on: [ push, pull_request ]

jobs:
  unit-scenario-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: Scenario Tests
        run: |
          cd ..
          rm -rf kitex-tests
          git clone https://github.com/cloudwego/kitex-tests.git
          cd kitex-tests
          ./run.sh ${{github.workspace}}
          cd ${{github.workspace}}

  benchmark-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Benchmark
        # we only use this CI to verify bench code works
        # setting benchtime=100ms is saving our time...
        run: go test -bench=. -benchmem -run=none ./... -benchtime=100ms

  compatibility-test:
    strategy:
      matrix:
        go: [ "1.17", "1.18", "1.19", "1.20", "1.21", "1.22" ]
        os: [ X64, ARM64 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false # don't use cache for self-hosted runners
      - name: Unit Test
        run: go test -race -covermode=atomic ./...

  codegen-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Prepare
        run: |  
          go install github.com/cloudwego/thriftgo@main
          go install ./tool/cmd/kitex
          LOCAL_REPO=$(pwd)
          cd ..
          git clone https://github.com/cloudwego/kitex-tests.git 
          cd kitex-tests/codegen
          go mod init codegen-test
          go mod edit -replace=github.com/apache/thrift=github.com/apache/thrift@v0.13.0
          go mod edit -replace github.com/cloudwego/kitex=${LOCAL_REPO}
          go mod tidy
          bash -version
          bash ./codegen_install_check.sh
      - name: CodeGen
        run: | 
          cd ../kitex-tests/codegen
          tree
          bash ./codegen_run.sh        

  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Windows compatibility test
        run: go test -run=^$ ./...
